### ISSUE TITLE
Error when make up the release

### ISSUE THREAD

**Issue by oscarlpez** [IDMEFv2/IDMEFv2-prototype#1]
Hi team

Just tried to put up and running the IDMEFv2-prototype. There is an error when tried to start with `make up` command. 
The error is the following.

`# make up` 

`(sudo podman-compose -p proto -f docker-compose.yml up 2>&1 1>>logs &)`

`# podman-compose version: 1.0.7` 
`['podman', '--version', '']`
`Traceback (most recent call last):`
<code>
File "/usr/local/bin/podman-compose", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/podman_compose.py", line 3246, in main
    asyncio.run(async_main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.10/dist-packages/podman_compose.py", line 3243, in async_main
    await podman_compose.run()
  File "/usr/local/lib/python3.10/dist-packages/podman_compose.py", line 1538, in run
    (await self.podman.output(["--version"], "", [])).decode("utf-8").strip()
  File "/usr/local/lib/python3.10/dist-packages/podman_compose.py", line 1173, in output
    p = await asyncio.subprocess.create_subprocess_exec(
  File "/usr/lib/python3.10/asyncio/subprocess.py", line 218, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1681, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "/usr/lib/python3.10/asyncio/unix_events.py", line 207, in _make_subprocess_transport
    transp = _UnixSubprocessTransport(self, protocol, args, shell,
  File "/usr/lib/python3.10/asyncio/base_subprocess.py", line 36, in __init__
    self._start(args=args, shell=shell, stdin=stdin, stdout=stdout,
  File "/usr/lib/python3.10/asyncio/unix_events.py", line 799, in _start
    self._proc = subprocess.Popen(
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'podman'
</code>

<br>
Seems like podman directory is not created but not sure where it should be created

Thanks a lot. Best regards.

Oscar

**Comment by Bytes-n-AI** [comment]
Podman seems to not be installed. Can you execute "podman --version" ?

If it is not installed, please install it and retry

**Comment by Bytes-n-AI** [comment]
I just add a check in be792fa54080c6224a71b4d5b0674d17dbd0c28e so you will get a proper error
